# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posta', '0002_auto_20171112_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatmaa',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
